s3:
  provider: localstack
  bucketName: bucket
  localstackUrl: http://localhost:4566

api:
  base:
    url:
      hmpps-auth: http://localhost:8090/auth

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: audit-queue

amendment.enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
