name: Security veracode pipeline scan

on:
  workflow_call:
    inputs:
      channel_id:
        required: false
        default: 'NO_SLACK'
        type: string
      docker_image_app_dir:
        required: false
        default: '/app'
        type: string
      veracode_package_artifact_name:
        required: false
        type: string
        default: ''
        description: "The name of the artifact to download, containing a veracode_artifact_name (default source.zip) packaged application. Optional."
      veracode_artifact_name:
        required: false
        type: string
        default: 'source.zip'
        description: "The name of the artifact within the package, Optional."
      java_version:
        type: string
        required: false
        default: '21'
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN:
        description: Slack bot token
        required: true
      HMPPS_VERACODE_API_ID_0:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_1:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_2:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_3:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_ID_4:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_0:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_1:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_2:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_3:
        description: Veracode app secret
        required: true
      HMPPS_VERACODE_API_KEY_4:
        description: Veracode app secret
        required: true

permissions:
  contents: read
  security-events: write

jobs:
  security-veracode-pipeline-scan:
    name: Security veracode pipeline scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    env:
      additional_docker_build_args: ""
      jdk_tag: "17.0"
      java_options: "-Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process"

    steps:
      - uses: actions/checkout@v6
      - name: Set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
      - name: prepare assets
        if: inputs.veracode_package_artifact_name == ''
        uses: ministryofjustice/hmpps-github-actions/.github/actions/security_veracode_prepare_artifacts@v2 # WORKFLOW_VERSION
        with:
          docker_image_app_dir: ${{ inputs.docker_image_app_dir }}
      - name: download assets artifact
        if: inputs.veracode_package_artifact_name != ''
        uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.veracode_package_artifact_name }}
      - name: "Download/Extract pipeline scanner"
        shell: bash
        run: |
          wget https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip -O pipeline-scan.zip
          unzip pipeline-scan.zip -x README.md
      - name: "Download Veracode Policy"
        shell: bash
        run: |
          echo "Randomly picking 1 of 5 api keys, to help avoid veracode API rate limits."
          X=$(( RANDOM % 4 ))
          VERACODE_API_ID_X="VERACODE_API_ID_${X}"
          VERACODE_API_KEY_X="VERACODE_API_KEY_${X}"
          VERACODE_API_ID="${!VERACODE_API_ID_X}"
          VERACODE_API_KEY="${!VERACODE_API_KEY_X}"
          echo "Using VERACODE_API_ID_${X} from pool (${VERACODE_API_ID:0:5}...)"
          java -jar pipeline-scan.jar \
          --request_policy "Ministry of Justice" \
          --veracode_api_id "${VERACODE_API_ID}" \
          --veracode_api_key "${VERACODE_API_KEY}"
        env:
          VERACODE_API_ID_0: ${{ secrets.HMPPS_VERACODE_API_ID_0 }}
          VERACODE_API_ID_1: ${{ secrets.HMPPS_VERACODE_API_ID_1 }}
          VERACODE_API_ID_2: ${{ secrets.HMPPS_VERACODE_API_ID_2 }}
          VERACODE_API_ID_3: ${{ secrets.HMPPS_VERACODE_API_ID_3 }}
          VERACODE_API_ID_4: ${{ secrets.HMPPS_VERACODE_API_ID_4 }}
          VERACODE_API_KEY_0: ${{ secrets.HMPPS_VERACODE_API_KEY_0 }}
          VERACODE_API_KEY_1: ${{ secrets.HMPPS_VERACODE_API_KEY_1 }}
          VERACODE_API_KEY_2: ${{ secrets.HMPPS_VERACODE_API_KEY_2 }}
          VERACODE_API_KEY_3: ${{ secrets.HMPPS_VERACODE_API_KEY_3 }}
          VERACODE_API_KEY_4: ${{ secrets.HMPPS_VERACODE_API_KEY_4 }}
      - name: "Scan the project"
        id: veracode-pipeline-scan
        shell: bash
        run: |
          echo "Randomly picking 1 of 5 api keys, to help avoid veracode API rate limits."
          X=$(( RANDOM % 4 ))
          VERACODE_API_ID_X="VERACODE_API_ID_${X}"
          VERACODE_API_KEY_X="VERACODE_API_KEY_${X}"
          VERACODE_API_ID="${!VERACODE_API_ID_X}"
          VERACODE_API_KEY="${!VERACODE_API_KEY_X}"
          echo "Using VERACODE_API_ID_${X} from pool (${VERACODE_API_ID:0:5}...)"
          java -jar pipeline-scan.jar \
          $(test -f results.json && echo "--baseline_file results.json") \
          --json_output true \
          --file ${{ inputs.veracode_artifact_name }} \
          --policy_file Ministry_of_Justice.json \
          --veracode_api_id "${VERACODE_API_ID}" \
          --veracode_api_key "${VERACODE_API_KEY}" \
          --timeout 60 \
          --issue_details false \
          --verbose true \
          --summary_output true
        continue-on-error: true
        env:
          VERACODE_API_ID_0: ${{ secrets.HMPPS_VERACODE_API_ID_0 }}
          VERACODE_API_ID_1: ${{ secrets.HMPPS_VERACODE_API_ID_1 }}
          VERACODE_API_ID_2: ${{ secrets.HMPPS_VERACODE_API_ID_2 }}
          VERACODE_API_ID_3: ${{ secrets.HMPPS_VERACODE_API_ID_3 }}
          VERACODE_API_ID_4: ${{ secrets.HMPPS_VERACODE_API_ID_4 }}
          VERACODE_API_KEY_0: ${{ secrets.HMPPS_VERACODE_API_KEY_0 }}
          VERACODE_API_KEY_1: ${{ secrets.HMPPS_VERACODE_API_KEY_1 }}
          VERACODE_API_KEY_2: ${{ secrets.HMPPS_VERACODE_API_KEY_2 }}
          VERACODE_API_KEY_3: ${{ secrets.HMPPS_VERACODE_API_KEY_3 }}
          VERACODE_API_KEY_4: ${{ secrets.HMPPS_VERACODE_API_KEY_4 }}
      - uses: actions/upload-artifact@v5
        id: veracode-artifact-upload
        if: success()
        continue-on-error: true
        with:
          name: veracode-pipeline-check-${{ github.event.repository.name }}
          path: results.txt
      - name: send a failure slack message
        if: steps.veracode-pipeline-scan.outcome == 'failure' && inputs.channel_id != 'NO_SLACK'
        uses: ministryofjustice/hmpps-github-actions/.github/actions/slack_failure_results@v2 # WORKFLOW_VERSION
        with:
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
          channel_id: ${{ inputs.channel_id }}
          input_file: results.txt

      - uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        if: steps.veracode-artifact-upload.conclusion == 'failure' && inputs.channel_id != 'NO_SLACK'
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ inputs.channel_id }}
            text: "Veracode pipeline scan failed"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ":no_entry: Failed GitHub Action:"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                  - type: mrkdwn
                    text: "*Job:*\n${{ github.job }}"
                  - type: mrkdwn
                    text: "*Repo:*\n${{ github.repository }}"
                  - type: mrkdwn
                    text: "*Project:*\n${{ github.event.repository.name }}"
