name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "22 9 * * MON-FRI" # Every weekday at 09:22 UTC
jobs:
  security-kotlin-owasp-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Kotlin security OWASP dependency check
    uses: ./.github/workflows/security_local_owasp.yml # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      nvd_feed_version: "2"
    secrets: inherit
