name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "2 7 * * MON-FRI" # Every weekday at 07:02 UTC
jobs:
  create-artifact:
    name: Build the artifact for veracode to scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    with:
      gradle-command: 'BUILD_NUMBER=veracode ./gradlew assemble'
      upload-build-artifacts: true
      java-version: "25"
      build-artifact-name: 'build-results'
      upload-test-artifacts: false
    permissions:
      contents: read
      actions: read
  security-veracode-pipeline-scan:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode pipeline scan
    uses: ./.github/workflows/security_veracode_pipeline_scan_local.yml
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      veracode_package_artifact_name: 'build-results'
      veracode_artifact_name: '${{ github.event.repository.name }}-veracode.jar'
      java_version: "25"
    secrets: inherit
    needs: create-artifact
